AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Metrics/LineLength:
  Max: 120
